import { Group, GroupDocument } from '../models/group.model.js';
import { BaseRepository } from './base.repository.js';
import { IGroup, IMemberProfile, IDietaryRestriction } from '../interfaces/index.js';
import { getNameSearchCollation } from '../config/index.js';

/**
 * Repository for managing Group documents
 */
export class GroupRepository extends BaseRepository<GroupDocument, IGroup> {
    constructor() {
        super(Group);
    }

    /**
     * Converts a Mongoose document to the public IGroup interface
     * @param doc The Group mongoose document
     * @returns The IGroup representation or null
     */
    protected toInterface(doc: GroupDocument | null): IGroup | null {
        if (!doc) return null;
        return doc.toObject() as unknown as IGroup;
    }

    /**
     * Finds a group by its exact name.
     * Uses configurable collation for user-friendly matching (e.g., case/accent insensitivity).
     * For optimal performance, ensure the `name` index is created with the same collation.
     * @param name The group name to look up
     * @returns The matching group or null
     */
    async findByName(name: string): Promise<IGroup | null> {
        const query = this.model.findOne({ name });
        const collation = getNameSearchCollation();
        if (collation) {
            query.collation(collation as any);
        }
        const doc = await query;
        return this.toInterface(doc);
    }

    /**
     * Adds a new member to the specified group
     * @param groupId The group ID
     * @param member The member profile to add (without id; generated by schema)
     * @returns The updated group or null if not found
     */
    async addMember(groupId: string, member: Omit<IMemberProfile, 'id'>): Promise<IGroup | null> {
        const doc = await this.model.findOneAndUpdate(
            { _id: groupId },
            {
                $push: { members: member },
                $set: { updatedAt: new Date() }
            },
            { new: true }
        );
        return this.toInterface(doc);
    }

    /**
     * Updates fields of a member inside a group using MongoDB dot-notation.
     * Nested objects are flattened up to a safe depth to avoid accidental overwrites.
     * @param groupId The group ID
     * @param memberId The member ID
     * @param update Partial member profile fields to update
     * @returns The updated group or null
     */
    async updateMember(groupId: string, memberId: string, update: Partial<IMemberProfile>): Promise<IGroup | null> {
        function processUpdate(
            obj: Record<string, any>,
            prefix: string = '',
            depth: number = 0
        ): Record<string, unknown> {
            const fields: Record<string, unknown> = {};
            const MAX_DEPTH = 3;

            if (depth >= MAX_DEPTH || !obj || typeof obj !== 'object') {
                fields[prefix] = obj;
                return fields;
            }

            for (const [key, value] of Object.entries(obj)) {
                const fullPath = prefix ? `${prefix}.${key}` : key;
                if (value && typeof value === 'object' && !Array.isArray(value)) {
                    Object.assign(fields, processUpdate(value, fullPath, depth + 1));
                } else {
                    fields[fullPath] = value;
                }
            }

            return fields;
        }

        // Transform the update object to use MongoDB's dot notation
        const processedFields = processUpdate(update, 'members.$');

        const doc = await this.model.findOneAndUpdate(
            {
                _id: groupId,
                'members._id': memberId
            },
            {
                $set: {
                    ...processedFields,
                    updatedAt: new Date()
                }
            },
            { new: true }
        );
        return this.toInterface(doc);
    }

    /**
     * Removes a member from a group
     * @param groupId The group ID
     * @param memberId The member ID to remove
     * @returns The updated group or null
     */
    async removeMember(groupId: string, memberId: string): Promise<IGroup | null> {
        const doc = await this.model.findByIdAndUpdate(
            groupId,
            {
                $pull: { members: { _id: memberId } },
                $set: { updatedAt: new Date() }
            },
            { new: true }
        );
        return this.toInterface(doc);
    }

    /**
     * Replaces the dietary restrictions array for a member
     * @param groupId The group ID
     * @param memberId The member ID
     * @param restrictions The full restrictions list to set
     * @returns The updated group or null
     */
    async updateMemberRestrictions(
        groupId: string,
        memberId: string,
        restrictions: IDietaryRestriction[]
    ): Promise<IGroup | null> {
        const doc = await this.model.findOneAndUpdate(
            {
                _id: groupId,
                'members._id': memberId
            },
            {
                $set: {
                    'members.$.dietaryProfile.restrictions': restrictions,
                    updatedAt: new Date()
                }
            },
            { new: true }
        );
        return this.toInterface(doc);
    }

    /**
     * Adds a single dietary restriction to a member
     * @param groupId The group ID
     * @param memberId The member ID
     * @param restriction The restriction to add
     * @returns The updated group or null
     */
    async addMemberRestriction(
        groupId: string,
        memberId: string,
        restriction: IDietaryRestriction
    ): Promise<IGroup | null> {
        const doc = await this.model.findOneAndUpdate(
            {
                _id: groupId,
                'members._id': memberId
            },
            {
                $push: { 'members.$.dietaryProfile.restrictions': restriction },
                $set: { updatedAt: new Date() }
            },
            { new: true }
        );
        return this.toInterface(doc);
    }

    /**
     * Removes a dietary restriction from a member by restriction id
     * @param groupId The group ID
     * @param memberId The member ID
     * @param restrictionId The restriction ID to remove
     * @returns The updated group or null
     */
    async removeMemberRestriction(
        groupId: string,
        memberId: string,
        restrictionId: string
    ): Promise<IGroup | null> {
        const doc = await this.model.findOneAndUpdate(
            {
                _id: groupId,
                'members._id': memberId
            },
            {
                $pull: { 'members.$.dietaryProfile.restrictions': { _id: restrictionId } },
                $set: { updatedAt: new Date() }
            },
            { new: true }
        );
        return this.toInterface(doc);
    }

    /**
     * Replaces the allergies array for a member
     * @param groupId The group ID
     * @param memberId The member ID
     * @param allergies The full allergies list to set
     * @returns The updated group or null
     */
    async updateMemberAllergies(
        groupId: string,
        memberId: string,
        allergies: string[]
    ): Promise<IGroup | null> {
        const doc = await this.model.findOneAndUpdate(
            {
                _id: groupId,
                'members._id': memberId
            },
            {
                $set: {
                    'members.$.dietaryProfile.allergies': allergies,
                    updatedAt: new Date()
                }
            },
            { new: true }
        );
        return this.toInterface(doc);
    }

    /**
     * Adds a single allergy entry to a member
     * @param groupId The group ID
     * @param memberId The member ID
     * @param allergy The allergy string to add
     * @returns The updated group or null
     */
    async addMemberAllergy(
        groupId: string,
        memberId: string,
        allergy: string
    ): Promise<IGroup | null> {
        const doc = await this.model.findOneAndUpdate(
            {
                _id: groupId,
                'members._id': memberId
            },
            {
                $push: { 'members.$.dietaryProfile.allergies': allergy },
                $set: { updatedAt: new Date() }
            },
            { new: true }
        );
        return this.toInterface(doc);
    }

    /**
     * Removes a single allergy entry from a member
     * @param groupId The group ID
     * @param memberId The member ID
     * @param allergy The allergy string to remove
     * @returns The updated group or null
     */
    async removeMemberAllergy(
        groupId: string,
        memberId: string,
        allergy: string
    ): Promise<IGroup | null> {
        const doc = await this.model.findOneAndUpdate(
            {
                _id: groupId,
                'members._id': memberId
            },
            {
                $pull: { 'members.$.dietaryProfile.allergies': allergy },
                $set: { updatedAt: new Date() }
            },
            { new: true }
        );
        return this.toInterface(doc);
    }
}
